<div class="modal fade modal-custom" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header row justify-content-center">
                <div class="col-12 modal-title mb-4 d-flex justify-content-center">
                    <h5 class="">Procurar usuário</h5>
                </div>
                <div class="col-6">
                    <form action="/chat_list?modal=search" method="get" class="form-row">
                        <input type="text" name="username" class="form-control input-custom-dark" id="inputSearchUser">
                    </form>
                </div>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-md-5" id="result_search">

                            <div class="card-user-search row justify-content-center" onclick="console.log('eae')">
                                <div class="col-12 row justify-content-end">
                                    João Paulo Gomes França
                                </div>
                                <div class="col-12 row justify-content-end">
                                    joaop
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




