<div class="container-fluid h-100 ">
	<div class="row h-100 justify-content-center">

        <div class="col-6 text-light">
            
            <form action="" method="post" id="form-create_account" enctype="multipart/form-data">
                <span class="h3 d-flex justify-content-center mb-5">Crie sua conta</span>
                <div class="row justify-content-center">
                    <!-- <div class="col-md-8 mb-4">
                        <input type="text" class="form-control input-custom-dark" name="name" placeholder="Nome Completo: ">
                    </div> -->

                    <div class="col-md-8 mb-4">
                        <input type="text" class="form-control input-custom-dark" name="name" placeholder="Nome Completo: ">
                    </div>
                    <div class="col-md-8 mb-4">
                        <input type="email" class="form-control input-custom-dark" name="email" placeholder="E-mail: ">
                    </div>
                    <hr class="bg-secondary col-md-6 mb-4">
                    <div class="col-md-8 mb-4">
                        <input type="text" class="form-control input-custom-dark" name="username" placeholder="Nome do usuário: ">
                    </div>
                    <div class="col-md-8 mb-4">
                        <input type="password" class="form-control input-custom-dark" name="password" placeholder="Senha: ">
                    </div>
                    <div class="col-md-8 mb-4">
                        <button type="submit" class="btn btn-block button-custom-1">Criar Conta</button>
                    </div>
                    <div class="mt-5">
                        <small>Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade</small>
                    </div>
                </div>
            </form>

        </div>

    </div>
</div>