<div class="container-fluid h-100 ">
	<div class="row h-100">

        <div class="col-md-6 left-side d-none d-md-block">
            <div class="row h-100 justify-content-center">
                <div class="text-light title-init-app">
                    <p class="display-5">Converse com pessoas novas hoje mesmo com o <spam class="title-app">Yooza</spam></p>
                </div>
                <div class="text-light mt-5 title-register-app d-none d-sm-block">
                    <p>Não conhece o <strong>Yooza</strong>? Crie uma conta e experimente agora!</p>
                    <span>
                        <a href="/create_account" class="btn btn-block button-custom-1">Criar Conta</a>
                    </span>
                </div>
            </div>
        </div>


        <div class="col-md-6 right-side">
            <div class="row h-100 justify-content-center">
                <div class="container">
                    <form class="form-login" action="/login" method="post">
                        <div class="">
                            <fieldset class="form-group row justify-content-around text-light">
                                <legend class="d-flex justify-content-center">Login</legend>

                                <div class="col-10 mt-5">
                                    <input type="text" class="form-control input-custom-dark" name="email" id="email_input" placeholder="E-mail: ">
                                </div>

                                <div class="col-10 mt-5">
                                    <input type="password" class="form-control input-custom-dark" name="password" id="password_input" placeholder="Senha: ">
                                </div>

                                <div class="col-10 mt-3">
                                    <p>
                                        Não conhece o <strong>Yooza?</strong> Crie uma <a href="/create_account">conta</a> e experimente agora!
                                    </p>
                                </div>
                                <div class="col-10 mt-3">
                                    <button type="submit" class="btn btn-block button-custom-1">Entrar</button>
                                </div>
                                <?php if($this->view->login == "error"){ ?>
                                    <small class="text-danger h5 mt-4">Email ou senha inválido(s).</small>
                                <?php } else if($this->view->login == "not_auth"){?>
                                    <small class="text-danger h5 mt-4">Faça login primeiro.</small>
                                <?php } ?>
                            </fieldset>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>