<div class="container-fluid h-100 ">
	<div class="row h-100 justify-content-center">

        <div class="col-6 text-light">

            <div class="border border-secondary rounded p-5 mt-5">
                <span class="h3 d-flex justify-content-center mb-5">Cadastro Realizado com sucesso</span>
                <a href="/" class="btn btn-block btn-success">Clique para voltar</a>
            </div>

        </div>

    </div>
</div>