<div class="container-fluid h-100">
	<div class="row h-100">

        
        
        <!-- Menu Lateral -->
         
         
        <aside class="col-4 col-md-1 row justify-content-start h-100 <?= isset($_GET['id_to']) ? 'd-none d-md-flex': '' ?>" id="menu_lateral-chat_list">

            <div class="col-md-12 row justify-content-center h-100 pb-4 pt-4 pr-0" id="icons_menu_lateral">
                <div class="col-md-12 align-self-start row justify-content-center p-0">
                    <a href="/chat_list">
                        <i class="text-light fa-solid fa-comment-dots fa-2xl"></i>
                    </a>
                </div>
                <div class="col-md-12 align-self-end row justify-content-center p-0">
                    <div class="col-md-12 row justify-content-center p-0 mt-3">
                        <a href="/logoff">
                            <i class="text-light fa-solid fa-arrow-right-from-bracket fa-2xl"></i>
                        </a>
                    </div>
                    <div class="col-md-12 align-self-end row justify-content-center p-0 mt-3">
                        <a href="#">
                            <i class="text-light fa-solid fa-gear fa-2x"></i>
                        </a>
                    </div>
                </div>
            </div>
            
        </aside>
       

        <!-- <aside class="d-flex flex-column justify-content-between align-items-center p-2" 
            id="menu_lateral-chat_list"
            style="width: 60px; height: 100vh; position: fixed; border-right: 3px solid #202020; border-radius: 0 10px 10px 0;">

            
            <div class="d-flex flex-column align-items-center mt-2">
                <a href="/chat_list" class="nav-link p-2">
                    <i class="text-light fa-solid fa-comment-dots fa-xl"></i>
                </a>
            </div>

            
            <div class="d-flex flex-column align-items-center mb-2">
                <a href="/logoff" class="nav-link p-2 mb-3">
                    <i class="text-light fa-solid fa-arrow-right-from-bracket fa-xl"></i>
                </a>
                <a href="#" class="nav-link p-2">
                    <i class="text-light fa-solid fa-gear fa-xl"></i>
                </a>
            </div>

        </aside> -->






        <section class="col-8 col-md-3 row justify-content-center h-100 <?= isset($_GET['id_to']) ? 'd-none d-md-flex': '' ?>" id="chat_list-chat_list">
            <div class="col-md-12 justify-content-center w-100">
                <div class="row justify-content-center align-items-center mt-3">
                    <div class="col-md-12 d-flex justify-content-center align-items-center p-3">
                        <a href="/chat_list?modal=search">
                            Pesquisar por um usuário
                        </a>
                    </div>
                </div>
                <hr class="col-10">
            </div>
        </section>

        <section class="col-12 col-md-8 h-100 <?= isset($_GET['id_to']) ? '': 'd-none d-md-flex' ?>" id="chat-chat_list">
            <!----- Chat ----->
            <?php if(isset($this->view->user_chat) && $this->view->user_chat != '') {?>


                <!-- Profile Top -->
                <div class="row profile-top">
                    <div class="col-1 d-flex justify-content-center">
                        <div class="ball"></div>
                    </div>
                    <div class="col-1 d-flex d-md-none align-items-center justify-content-center">
                        <a href="/chat_list" class="text-light">
                            <i class="fa-solid fa-chevron-left"></i>
                        </a>
                    </div>
                    <?php if(isset($_GET['id_to'])){?>
                    <?php }?>
                    <div class="col justify-content-end align-items-center">
                        <div class="row">
                            <?=$this->view->user_chat['name']?>
                        </div>
                        <div class="row">
                            <?=$this->view->user_chat['username']?>
                        </div>
                    </div>
                </div>

            
                
                <!-- Messages -->
                <div class="row messages text-light">
                    <div class="col-12">
                    </div>
                </div>

                <!-- Input Chat -->
                <div class="row input_chat text-light ">
                    <div class="col-12">
                        <form action="/message" method="post" class="d-flex px-3 py-2 gap-2">
                            <input type="hidden" name="id_to" value="<?=$_GET['id_to'] ?? "" ?>">
                            <input type="hidden" name="action" value="send">
                            <input type="text" name="msg" class="form-control input-custom-dark chat-input" placeholder="Digite sua mensagem..." autocomplete="off">
                            <button type="submit" class="btn btn-custom">
                                <i class="text-light fa-solid fa-paper-plane fa-xl"></i>
                            </button>
                        </form>
                    </div>
                </div>
            <?php }?>


        </section>
    </div>
</div>

<div id="custom_menu_mouse">
    <ul>
        <li onclick="this.querySelector('form').submit()">
            <form action="/message" method="POST">
                <input type="hidden" name="action" value="del">
                <input type="hidden" id="id_message" name="id" value="">
                <input type="hidden" name="id_to" value="<?= $_GET['id_to']?>">
                <span>Apagar</span>
            </form>
        </li>
        <li id="editMessageLI">
            <span>Editar</span>
        </li>
    </ul>
</div>